#!/usr/bin/env python3
"""OSM named streets (Overpass JSON, qa/tools/data/coney-streets.json) -> src/world/coney/streetnames.js: the street-name sign
text for every road the map draws (Coney + Brighton), as simplified polylines in the map frame. Street names are public
geography (not brands), so they ship as they are, in the NYC sign style: "W 12 St", "Surf Av", "Brighton Beach Av".
Fetch: [out:json];way["highway"]["name"](40.566,-74.0,40.582,-73.955);out geom tags;
Usage: python3 qa/tools/osm-streets.py qa/tools/data/coney-streets.json src/world/coney/streetnames.js"""
import json, math, re, sys
src, out = sys.argv[1], sys.argv[2]
LAT0, LON0 = 40.5745, -73.9800
kx = 111320 * math.cos(math.radians(LAT0)); ky = 110540; TH = math.radians(8.33)
def P(lat, lon):
    x = (lon - LON0) * kx; z = -(lat - LAT0) * ky
    return [round(x * math.cos(TH) - z * math.sin(TH), 1), round(x * math.sin(TH) + z * math.cos(TH), 1)]
KEEP = {'primary', 'secondary', 'tertiary', 'residential', 'unclassified', 'living_street', 'trunk', 'pedestrian'}
def nyc(name):   # NYC street-sign abbreviations
    n = name
    for a, b in [(r'\bWest\b', 'W'), (r'\bEast\b', 'E'), (r'\bNorth\b', 'N'), (r'\bSouth\b', 'S'), (r'\bStreet\b', 'St'), (r'\bAvenue\b', 'Av'), (r'\bPlace\b', 'Pl'),
                 (r'\bRoad\b', 'Rd'), (r'\bBoulevard\b', 'Blvd'), (r'\bParkway\b', 'Pkwy'), (r'\bCourt\b', 'Ct'), (r'\bTerrace\b', 'Ter'), (r'\bWalk\b', 'Walk'),
                 (r'(\d+)(st|nd|rd|th)\b', r'\1')]:
        n = re.sub(a, b, n)
    return n
d = json.load(open(src))['elements']
rows = []
for e in d:
    t = e.get('tags', {}); hw = t.get('highway'); name = t.get('name')
    if hw not in KEEP or not name or not e.get('geometry'): continue
    pts = [P(g['lat'], g['lon']) for g in e['geometry']]
    if not any(-460 < x < 2420 and -600 < z < 160 for x, z in pts): continue
    rows.append({'n': nyc(name), 'p': pts})
js = '// GENERATED by qa/tools/osm-streets.py from OpenStreetMap (ODbL, (c) OpenStreetMap contributors). Do not edit by hand.\n'
js += '// Street names (NYC sign style) along their polylines, map frame (metres): what the corner signs say. {n, p: [[x, z], …]}\n'
js += 'export const STREET_NAMES = ' + json.dumps(rows, ensure_ascii=False, separators=(',', ':')) + ';\n'
open(out, 'w').write(js)
print(len(rows), 'named streets ->', out, sorted({r['n'] for r in rows})[:60])
