// Descriptive catalog; numerical parameters live beside the model rules that use them.
export const RENDER_POLICY_VERSION=7;
export const RENDER_INVARIANTS=[
  'Source observations and merge decisions are immutable. Keep all measured alternatives available, including represented records and unknown fields.',
  'Gathering and the 2D preview resolve source observations only. Generate 3D prepares models; only rendering derives defaults, interpolates heights, extrapolates supported models, places geometry or excludes visual instances. Record estimated dimensions and the measurements used in a separate render log.',
  'Unknown or conflicting source evidence may remain an outline instead of a guessed solid. A model estimate never becomes independent evidence for source fidelity selection.',
];
export const RENDER_POLICIES=[
  {id:'points',name:'Measured point selection',description:'Query retained decoded LAS records by explicit native XYZ bounds, numeric classification and origin IDs. Return complete measured records and source/asset identity; preserve the full source cloud and merge log. Reject incomplete decoding or result-limit overflow instead of returning a truncated cloud. Native point queries do not transform coordinates, align datums or reconstruct surfaces/supports.'},
  {id:'structures',name:'Standalone structure references',description:'Keep unmapped physical placement for explicit man_made structures as inspectable outlines, including closed piers, breakwaters, masts and towers. Retain tagged measured dimensions; a closed outline alone does not create a land surface or certify a solid.'},
  {id:'lighting',name:'Untextured inspection lighting',description:'Use diffuse Lambert vertex lighting for solid surfaces, terrain and props. Preserve source geometry, material colors, side settings and instance attributes. Physical surface finish is not measured; textured or reflective materials require separate render rules.'},
  {id:'dimensions',name:'Default dimensions',description:'Estimate building heights from tagged floor counts, road widths from matched LION ranges or lanes, and missing prop/curb/tree/rail dimensions from explicit rules. Preserve measured values; classification and default dimensions stay flagged as estimates. Keep relation and member templates until rendering compares an explicit outer-member relationship with identical footprint, holes and compatible bases; prefer a usable measured member height over an estimated relation height. Retain both envelopes and log contradictions or ambiguity.'},
  {id:'elevation',name:'Ground, bridge and ramp models',description:'Associate actual spot observations by role, build estimated terrain/deck profiles, and connect ramps through measured or terrain anchors at exact graph nodes. Keep separate bridge levels and bounded support intervals. Layer tags give order, never metres.'},
  {id:'equipment',name:'Native roofs, tanks and supports',description:'Select native versus current surfaces from retained measured alternatives, rigidly rebase compatible native roofs, audit native edge/vertex topology and intersections, and cap area cuts only for meshes passing the solid audit. Native roof walking remains unsupported; building walls use a separately logged estimated footprint collision proxy. Attach measured tank envelopes after parent/roof checks and construct eligible mapped pylon frames. Datum alignment, generated caps, wall/member shape and support bases remain estimates. Unmeasured regular train/highway columns remain gaps.'},
  {id:'placement',name:'Placement and visual clearance',description:'Record actual terrain/reference-plane placement separately. Replace a whole-building volume only when eligible parts cover its complete footprint and base, including holes, and retain its maximum height envelope. Use retained original geographic rings for assembly coverage so projection curvature cannot invent gaps at added vertices. Place accepted parts from a shared estimated parent base; incomplete or ambiguous assemblies remain references. Extrusion collision heights use the actual drawn Float32 bounds. Choose among retained measured tree positions using modeled surface clearance, space tree-row instances and exclude visual trees from rendered road/path surfaces. Preserve the complete source geometry and observations.'},
];
